# Generated by Django 2.2 on 2021-01-23 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='last_time_search',
            new_name='entry_time',
        ),
    ]
